/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.despegar.sem.connect.mystique;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ErdosType { 
  UPA, TRACKEAME, SOCIAL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ErdosType\",\"namespace\":\"com.despegar.sem.connect.mystique\",\"symbols\":[\"UPA\",\"TRACKEAME\",\"SOCIAL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
