/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.despegar.sem.connect.mystique;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ErdosTag { 
  TRACKEAME_PAGEVIEW, FB_SOFT_LOGIN, CRITEO  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ErdosTag\",\"namespace\":\"com.despegar.sem.connect.mystique\",\"symbols\":[\"TRACKEAME_PAGEVIEW\",\"FB_SOFT_LOGIN\",\"CRITEO\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
